import {
	index,
	type RouteConfig,
	route,
} from "@react-router/dev/routes";

export default [
	index("routes/_index.tsx"),
	route(
		"admin/migrate/relationships",
		"routes/admin/migrate/relationships/_index.tsx",
	),
	route("admin/storage/avatars", "routes/admin/storage/avatars/_index.tsx"),
	route("admin/storage/minutes", "routes/admin/storage/minutes/_index.tsx"),
	route("admin/storage/receipts", "routes/admin/storage/receipts/_index.tsx"),
	route("analytics", "routes/analytics/_index.tsx"),
	route(
		"api.entities.import-from-source",
		"routes/api.entities.import-from-source.tsx",
	),
	route("api.relationships.analyze", "routes/api.relationships.analyze.tsx"),
	route("api.risc.receiver", "routes/api.risc.receiver.tsx"),
	route("api/analytics/analyze", "routes/api/analytics/analyze/_index.tsx"),
	route("api/analytics/export", "routes/api/analytics/export/_index.tsx"),
	route("api/analytics/questions", "routes/api/analytics/questions/_index.tsx"),
	route("api/avatar/set", "routes/api/avatar/set/_index.tsx"),
	route("api/avatars/delete", "routes/api/avatars/delete/_index.tsx"),
	route("api/files/delete-temp", "routes/api/files/delete-temp/_index.tsx"),
	route("api/files/upload-temp", "routes/api/files/upload-temp/_index.tsx"),
	route("api/files/upload-token", "routes/api/files/upload-token/_index.tsx"),
	route(
		"treasury/budgets/:budgetId/delete",
		"routes/treasury/budgets/$budgetId/delete/_index.tsx",
	),
	route("api/drafts/cleanup", "routes/api/drafts/cleanup/_index.tsx"),
	route(
		"api/entities/create-draft",
		"routes/api/entities/create-draft/_index.tsx",
	),
	route(
		"api/entities/smart-autofill",
		"routes/api/entities/smart-autofill/_index.tsx",
	),
	route("api/entities/:type/:id", "routes/api/entities/$type.$id/_index.tsx"),
	route("faq/:faqId/delete", "routes/faq/$faqId/delete/_index.tsx"),
	route("api/faq/:faqId/update", "routes/api/faq/$faqId/update/_index.tsx"),
	route(
		"api/inventory/:itemId/complete",
		"routes/api/inventory/$itemId/complete/_index.tsx",
	),
	route(
		"api/inventory/:itemId/update",
		"routes/api/inventory/$itemId/update/_index.tsx",
	),
	route("api/inventory/export", "routes/api/inventory/export/_index.tsx"),
	route("api/inventory/import", "routes/api/inventory/import/_index.tsx"),
	route("api/messages/mark-read", "routes/api/messages/mark-read/_index.tsx"),
	route("api/minutes", "routes/api/minutes/_index.tsx"),
	route(
		"minutes/:minuteId/delete",
		"routes/minutes/$minuteId/delete/_index.tsx",
	),
	route(
		"api/minutes/:minuteId/update",
		"routes/api/minutes/$minuteId/update/_index.tsx",
	),
	route("api/minutes/upload", "routes/api/minutes/upload/_index.tsx"),
	route("news/:newsId/delete", "routes/news/$newsId/delete/_index.tsx"),
	route("api/news/:newsId/update", "routes/api/news/$newsId/update/_index.tsx"),
	route("api/receipts/:receiptId", "routes/api/receipts/$receiptId/_index.tsx"),
	route(
		"api/receipts/:receiptId/ingest",
		"routes/api/receipts/$receiptId/ingest/_index.tsx",
	),
	route(
		"treasury/receipts/:receiptId/delete",
		"routes/treasury/receipts/$receiptId/delete/_index.tsx",
	),
	route(
		"api/receipts/:receiptId/process",
		"routes/api/receipts/$receiptId/process/_index.tsx",
	),
	route("api/receipts/analyze", "routes/api/receipts/analyze/_index.tsx"),
	route("api/receipts/delete", "routes/api/receipts/delete/_index.tsx"),
	route("api/receipts/ocr", "routes/api/receipts/ocr/_index.tsx"),
	route("api/receipts/rename", "routes/api/receipts/rename/_index.tsx"),
	route("api/receipts/thumbnail", "routes/api/receipts/thumbnail/_index.tsx"),
	route("api/receipts/upload", "routes/api/receipts/upload/_index.tsx"),
	route(
		"treasury/reimbursements/:reimbursementId/delete",
		"routes/treasury/reimbursements/$reimbursementId/delete/_index.tsx",
	),
	route(
		"api/reimbursements/:reimbursementId/update",
		"routes/api/reimbursements/$reimbursementId/update/_index.tsx",
	),
	route(
		"api/relationship/analyze",
		"routes/api/relationship/analyze/_index.tsx",
	),
	route("api/set-language", "routes/api/set-language/_index.tsx"),
	route("api/set-theme-palette", "routes/api/set-theme-palette/_index.tsx"),
	route(
		"treasury/transactions/:transactionId/delete",
		"routes/treasury/transactions/$transactionId/delete/_index.tsx",
	),
	route(
		"api/transactions/:transactionId/update",
		"routes/api/transactions/$transactionId/update/_index.tsx",
	),
	route("api/treasury/export", "routes/api/treasury/export/_index.tsx"),
	route("api/treasury/import", "routes/api/treasury/import/_index.tsx"),
	route("api/webhooks/resend", "routes/api/webhooks/resend/_index.tsx"),
	route("auth/callback", "routes/auth/callback/_index.tsx"),
	route("auth/login", "routes/auth/login/_index.tsx"),
	route("auth/logout", "routes/auth/logout/_index.tsx"),
	route("committee", "routes/committee/_index.tsx"),
	route("committee/mail", "routes/committee/mail/_index.tsx"),
	route("contact", "routes/contact/_index.tsx"),
	route("events", "routes/events/_index.tsx"),
	route("events/:eventId/delete", "routes/events/$eventId/delete/_index.tsx"),
	route("events/:eventId/edit", "routes/events/$eventId/edit/_index.tsx"),
	route("events/new", "routes/events/new/_index.tsx"),
	route("faq", "routes/faq/_index.tsx"),
	route("faq/:faqId", "routes/faq/$faqId/_index.tsx"),
	route("faq/:faqId/edit", "routes/faq/$faqId/edit/_index.tsx"),
	route("inventory", "routes/inventory/_index.tsx"),
	route("inventory/:itemId", "routes/inventory/$itemId/_index.tsx"),
	route(
		"inventory/:itemId/delete",
		"routes/inventory/$itemId/delete/_index.tsx",
	),
	route("inventory/:itemId/edit", "routes/inventory/$itemId/edit/_index.tsx"),
	route("inventory/incomplete", "routes/inventory/incomplete/_index.tsx"),
	route("mail", "routes/mail.tsx", [
		index("routes/mail/_index.tsx"),
		route("inbox", "routes/mail/inbox/_index.tsx"),
		route("messages/:messageId", "routes/mail/messages/$messageId/_index.tsx"),
		route("compose", "routes/mail/compose/_index.tsx"),
		route("drafts", "routes/mail/drafts/_index.tsx"),
		route(
			"drafts/:draftId/edit",
			"routes/mail/drafts/$draftId/edit/_index.tsx",
		),
		route("new", "routes/mail/new/_index.tsx"),
		route("thread/:threadId", "routes/mail/thread/$threadId/_index.tsx"),
	]),
	route("messages", "routes/messages/_index.tsx"),
	route("minutes", "routes/minutes/_index.tsx"),
	route("minutes/:minuteId", "routes/minutes/$minuteId/_index.tsx"),
	route("minutes/:minuteId/edit", "routes/minutes/$minuteId/edit/_index.tsx"),
	route("news", "routes/news/_index.tsx"),
	route("news/:newsId", "routes/news/$newsId/_index.tsx"),
	route("news/:newsId/edit", "routes/news/$newsId/edit/_index.tsx"),
	route("polls", "routes/polls/_index.tsx"),
	route("polls/:pollId/delete", "routes/polls/$pollId/delete/_index.tsx"),
	route("polls/:pollId/edit", "routes/polls/$pollId/edit/_index.tsx"),
	route("polls/analytics", "routes/polls/analytics/_index.tsx"),
	route("polls/new", "routes/polls/new/_index.tsx"),
	route("profile", "routes/profile/_index.tsx"),
	route("settings/analytics", "routes/settings/analytics/_index.tsx"),
	route("settings/auto-input", "routes/settings/auto-input/_index.tsx"),
	route("settings/faqs", "routes/settings/faqs/_index.tsx"),
	route("settings/general", "routes/settings/general/_index.tsx"),
	route("settings/news", "routes/settings/news/_index.tsx"),
	route("settings/receipts", "routes/settings/receipts/_index.tsx"),
	route("settings/reimbursements", "routes/settings/reimbursements/_index.tsx"),
	route(
		"settings/relationship-contexts",
		"routes/settings/relationship-contexts/_index.tsx",
	),
	route("settings/roles", "routes/settings/roles/_index.tsx"),
	route("settings/users", "routes/settings/users/_index.tsx"),
	route("setup", "routes/setup/_index.tsx"),
	route("social", "routes/social/_index.tsx"),
	route("social/new", "routes/social/new/_index.tsx"),
	route("submissions", "routes/submissions/_index.tsx"),
	route(
		"submissions/:submissionId/delete",
		"routes/submissions/$submissionId/delete/_index.tsx",
	),
	route("treasury", "routes/treasury/_index.tsx"),
	route("treasury/breakdown", "routes/treasury/breakdown/_index.tsx"),
	route("treasury/budgets", "routes/treasury/budgets/_index.tsx"),
	route(
		"treasury/budgets/:budgetId",
		"routes/treasury/budgets/$budgetId/_index.tsx",
	),
	route(
		"treasury/budgets/:budgetId/edit",
		"routes/treasury/budgets/$budgetId/edit/_index.tsx",
	),
	route("treasury/receipts", "routes/treasury/receipts/_index.tsx"),
	route(
		"treasury/receipts/:receiptId",
		"routes/treasury/receipts/$receiptId/_index.tsx",
	),
	route(
		"treasury/receipts/:receiptId/edit",
		"routes/treasury/receipts/$receiptId/edit/_index.tsx",
	),
	route("treasury/reimbursements", "routes/treasury/reimbursements/_index.tsx"),
	route(
		"treasury/reimbursements/:reimbursementId",
		"routes/treasury/reimbursements/$reimbursementId/_index.tsx",
	),
	route(
		"treasury/reimbursements/:reimbursementId/edit",
		"routes/treasury/reimbursements/$reimbursementId/edit/_index.tsx",
	),
	route("treasury/transactions", "routes/treasury/transactions/_index.tsx"),
	route(
		"treasury/transactions/:transactionId",
		"routes/treasury/transactions/$transactionId/_index.tsx",
	),
	route(
		"treasury/transactions/:transactionId/edit",
		"routes/treasury/transactions/$transactionId/edit/_index.tsx",
	),
] satisfies RouteConfig;
